site_name: Courtside Data
site_url: https://nickth3man.github.io/courtside-data
site_author: Nicolas Alexander
repo_name: nickth3man/courtside-data
repo_url: https://github.com/nickth3man/courtside-data
nav:
  - Home: index.md
  - Architecture:
      - Endpoint Runtime: architecture/endpoints.md
  - API:
      - Schemas: api/schemas.md
      - Endpoints: api/endpoints.md
theme: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [courtside_data]
          options:
            docstring_style: google
            extensions:
              - griffe_pydantic:
                  schema: true
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.magiclink
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.superfences
  - toc:
      permalink: true
