/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/endpoints/player-hub": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_endpoints_player_hub_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Search */
        get: operations["player_search_api_players_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_identifier}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Summary */
        get: operations["player_summary_api_players__player_identifier__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_identifier}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Dataset */
        get: operations["export_dataset_api_players__player_identifier__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_identifier}/seasons/{season_end_year}/{dataset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season Dataset */
        get: operations["season_dataset_api_players__player_identifier__seasons__season_end_year___dataset__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_identifier}/{dataset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Dataset */
        get: operations["player_dataset_api_players__player_identifier___dataset__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/endpoints/team-hub": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Team Catalog
         * @description Static Team Hub catalog: tabs and dataset metadata.
         */
        get: operations["team_catalog_api_endpoints_team_hub_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Team Search
         * @description Search teams by name/abbreviation.
         *
         *     Mirrors ``/api/players/search`` but filters to team results.
         */
        get: operations["team_search_api_teams_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_identifier}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Team Summary
         * @description Aggregated Team Hub overview payload.
         *
         *     Mirrors ``/api/players/{player_identifier}/summary`` for team data.
         */
        get: operations["team_summary_api_teams__team_identifier__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_identifier}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Team Export
         * @description Stream a Team Hub dataset as a CSV download.
         *
         *     Mirrors ``/api/players/{player_identifier}/export`` for team datasets.
         */
        get: operations["team_export_api_teams__team_identifier__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_identifier}/seasons/{season_end_year}/{dataset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Team Season Dataset
         * @description Team-season-scoped dataset (requires ``season_end_year`` in the URL).
         */
        get: operations["team_season_dataset_api_teams__team_identifier__seasons__season_end_year___dataset__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_identifier}/{dataset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Team Dataset
         * @description Team-scoped dataset (no season in the URL).
         */
        get: operations["team_dataset_api_teams__team_identifier___dataset__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiError
         * @description Stable error response returned by the Player Hub API.
         */
        ApiError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /**
         * ColumnMeta
         * @description Presentation metadata for one response column.
         */
        ColumnMeta: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Default Visible
             * @default true
             */
            default_visible: boolean;
            /**
             * Numeric
             * @default false
             */
            numeric: boolean;
        };
        /**
         * EndpointRowsResponse
         * @description Rows returned by one endpoint-backed dataset.
         */
        EndpointRowsResponse: {
            /** Dataset */
            dataset: string;
            /** Endpoint Name */
            endpoint_name: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Row Count */
            row_count: number;
            /** Columns */
            columns: components["schemas"]["ColumnMeta"][];
            /** Default Visible Columns */
            default_visible_columns: string[];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /**
             * Transport
             * @enum {string}
             */
            transport: "fixture" | "live";
        };
        /**
         * FranchiseArcPoint
         * @description A single point on the franchise-level season arc.
         *
         *     Sourced from the ``franchise_history`` endpoint's
         *     :class:`~courtside_data.schemas.teams.FranchiseHistoryRow`. The
         *     point carries the season-end-year, the team name (which can
         *     differ across the arc for relocated / renamed franchises, e.g.
         *     the Seattle SuperSonics -> OKC Thunder), and the win-loss
         *     summary. ``win_pct`` is computed by the service
         *     (``wins / (wins + losses)`` when both are positive; ``None``
         *     otherwise).
         */
        FranchiseArcPoint: {
            /** Season End Year */
            season_end_year: number;
            /** Team Name */
            team_name?: string | null;
            /** Wins */
            wins?: number | null;
            /** Losses */
            losses?: number | null;
            /** Win Pct */
            win_pct?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PlayerHubSummary
         * @description Aggregated overview payload for the Player Hub landing state.
         */
        PlayerHubSummary: {
            /** Identifier */
            identifier: string;
            /** Display Name */
            display_name: string;
            /** Leagues */
            leagues?: string[];
            /** Default Season */
            default_season?: number | null;
            /** Available Seasons */
            available_seasons?: number[];
            /** Hero Stats */
            hero_stats?: {
                [key: string]: unknown;
            };
            career: components["schemas"]["EndpointRowsResponse"];
            /** Season Dataset Availability */
            season_dataset_availability?: {
                [key: string]: number[];
            };
            /**
             * Transport
             * @enum {string}
             */
            transport: "fixture" | "live";
        };
        /**
         * PlayerSearchResult
         * @description Player result shown in the UI search control.
         */
        PlayerSearchResult: {
            /** Name */
            name: string;
            /** Identifier */
            identifier: string;
            /** Leagues */
            leagues?: string[];
        };
        /**
         * StatusResponse
         * @description Health and runtime metadata for the UI shell.
         */
        StatusResponse: {
            /** Ok */
            ok: boolean;
            /**
             * Transport
             * @enum {string}
             */
            transport: "fixture" | "live";
            /** Endpoint Count */
            endpoint_count: number;
            /** Fixture Root */
            fixture_root?: string | null;
            /** Fixture Root Exists */
            fixture_root_exists?: boolean | null;
        };
        /**
         * TeamDatasetCatalogEntry
         * @description HTTP-facing metadata for one Team Hub dataset.
         *
         *     Mirrors :class:`DatasetCatalogEntry` but uses the team-scope literal
         *     (``"team"`` / ``"team_season"``) instead of the player-scope literal.
         */
        TeamDatasetCatalogEntry: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Endpoint Name */
            endpoint_name: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "team" | "team_season";
            /** Description */
            description: string;
            /** Columns */
            columns?: unknown[];
            /** Default Visible Columns */
            default_visible_columns?: string[];
            /**
             * Supports Export
             * @default true
             */
            supports_export: boolean;
        };
        /**
         * TeamHeroStats
         * @description Closed-type hero-stats payload for the Team Hub landing state.
         *
         *     Mirrors the player-hub's :class:`PlayerHubSummary` ``hero_stats``
         *     payload but typed: ``team`` is the only required field (always
         *     populated with the requested team identifier so a missing-fixture
         *     path still tells the UI which team the empty stats are for); every
         *     other field is ``Optional`` and defaults to ``None``. This is the
         *     graceful-empty contract — the UI can render "no data" without
         *     guarding on shape.
         */
        TeamHeroStats: {
            /** Team */
            team: string;
            /** Season */
            season?: number | string | null;
            /** Wins */
            wins?: number | null;
            /** Losses */
            losses?: number | null;
            /** Win Pct */
            win_pct?: number | null;
            /** Wins Pyth */
            wins_pyth?: number | null;
            /** Losses Pyth */
            losses_pyth?: number | null;
            /** Mov */
            mov?: number | null;
            /** Srs */
            srs?: number | null;
            /** Off Rtg */
            off_rtg?: number | null;
            /** Def Rtg */
            def_rtg?: number | null;
            /** Pace */
            pace?: number | null;
        };
        /**
         * TeamHubCatalog
         * @description Top-level Team Hub catalog response.
         *
         *     Shape mirrors :class:`PlayerHubSummary` in spirit (hub landing payload)
         *     but exposes the static tab/dataset metadata that the UI uses to render
         *     the hub shell.
         */
        TeamHubCatalog: {
            /** Tabs */
            tabs: components["schemas"]["TeamHubTab"][];
            /** Datasets */
            datasets: components["schemas"]["TeamDatasetCatalogEntry"][];
        };
        /**
         * TeamHubSummary
         * @description Aggregated overview payload for the Team Hub landing state.
         *
         *     Mirrors :class:`PlayerHubSummary`; the embedded ``roster`` field plays
         *     the same structural role as the player hub's ``career`` field.
         */
        TeamHubSummary: {
            /** Identifier */
            identifier: string;
            /** Display Name */
            display_name: string;
            /** Leagues */
            leagues?: string[];
            /** Default Season */
            default_season?: number | null;
            /** Available Seasons */
            available_seasons?: number[];
            hero_stats?: components["schemas"]["TeamHeroStats"];
            roster: components["schemas"]["EndpointRowsResponse"];
            /** Season Dataset Availability */
            season_dataset_availability?: {
                [key: string]: number[];
            };
            /** Franchise Arc */
            franchise_arc?: components["schemas"]["FranchiseArcPoint"][];
            /**
             * Transport
             * @enum {string}
             */
            transport: "fixture" | "live";
        };
        /**
         * TeamHubTab
         * @description A tab and its backing datasets in the Team Hub.
         */
        TeamHubTab: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "team" | "team_season";
            /** Datasets */
            datasets: string[];
            /** Default Dataset */
            default_dataset: string;
        };
        /**
         * TeamSearchResult
         * @description Team result shown in the UI search control.
         */
        TeamSearchResult: {
            /** Name */
            name: string;
            /** Identifier */
            identifier: string;
            /** Leagues */
            leagues?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    catalog_api_endpoints_player_hub_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    player_search_api_players_search_get: {
        parameters: {
            query: {
                term: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSearchResult"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    player_summary_api_players__player_identifier__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerHubSummary"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    export_dataset_api_players__player_identifier__export_get: {
        parameters: {
            query: {
                dataset: string;
                season_end_year?: number | null;
                include_inactive_games?: boolean;
            };
            header?: never;
            path: {
                player_identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    season_dataset_api_players__player_identifier__seasons__season_end_year___dataset__get: {
        parameters: {
            query?: {
                include_inactive_games?: boolean;
            };
            header?: never;
            path: {
                player_identifier: string;
                season_end_year: number;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointRowsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    player_dataset_api_players__player_identifier___dataset__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_identifier: string;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointRowsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    team_catalog_api_endpoints_team_hub_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamHubCatalog"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    team_search_api_teams_search_get: {
        parameters: {
            query: {
                term: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSearchResult"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    team_summary_api_teams__team_identifier__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamHubSummary"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    team_export_api_teams__team_identifier__export_get: {
        parameters: {
            query: {
                dataset: string;
                season_end_year?: number | null;
                include_inactive_games?: boolean;
            };
            header?: never;
            path: {
                team_identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    team_season_dataset_api_teams__team_identifier__seasons__season_end_year___dataset__get: {
        parameters: {
            query?: {
                include_inactive_games?: boolean;
            };
            header?: never;
            path: {
                team_identifier: string;
                season_end_year: number;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointRowsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    team_dataset_api_teams__team_identifier___dataset__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_identifier: string;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointRowsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
