"""Build a detailed CSV inventory of Basketball-Reference page families
discovered by the librarian agent that are NOT currently covered by the
``raw/`` corpus or ``courtside_data.endpoints.ENDPOINTS``.

Output: ``docs/bref_new_page_families.csv``

Columns
-------
page_family           : canonical BREF name
category              : topical category (League / Playoffs / Team / Player / ...)
tier                  : P2_new | P1_duplicate | P2_disallowed | off_domain
robots_status         : allowed | disallowed | crawl_delay | off_domain
canonical_pattern     : URL template with {placeholders}
sample_url            : representative URL
primary_table_id_s    : BREF <table id="...">(s) or "unknown"
resembles_endpoint    : existing ENDPOINTS key this maps to (if any)
description           : one-line summary of what's on the page
parser_requirements   : notes for the parser engineer
librarian_row         : row number in the librarian's source table

Run:  python -m scripts.build_bref_inventory_csv
"""
from __future__ import annotations

import csv
from collections.abc import Sequence
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "bref_new_page_families.csv"

# ---------------------------------------------------------------------------
# Source data — transcribed from the librarian agent's Basketball-Reference
# inventory (90 NBA men's pro page families + adjacent-domain flags).
# Tuple format: (page_family, category, tier, robots_status, canonical_pattern,
#                sample_url, primary_table_id_s, resembles_endpoint,
#                description, parser_requirements, librarian_row)
# ---------------------------------------------------------------------------

ROWS: list[tuple[str, str, str, str, str, str, str, str, str, str, int]] = [
    # ── Franchise / team year-by-year + historical (1-17) ──
    ("franchise_year_by_year_stats_totals", "Team", "P2_new", "allowed",
     "/teams/{ID}/stats_basic_totals.html",
     "https://www.basketball-reference.com/teams/ATL/stats_basic_totals.html",
     "unknown (needs page fetch)",
     "team_and_opponent",
     "All-time franchise totals across every season in one large table.",
     "Trivial table scrape; row shape overlaps team_and_opponent per-season rows.",
     1),
    ("franchise_year_by_year_stats_per_game", "Team", "P2_new", "allowed",
     "/teams/{ID}/stats_per_game_totals.html",
     "https://www.basketball-reference.com/teams/ATL/stats_per_game_totals.html",
     "unknown (needs page fetch)",
     "league_per_game_stats",
     "All-time franchise per-game averages across every season.",
     "Trivial table scrape.",
     2),
    ("franchise_year_by_year_opp_totals", "Team", "P2_new", "allowed",
     "/teams/{ID}/opp_stats_basic_totals.html",
     "https://www.basketball-reference.com/teams/ATL/opp_stats_basic_totals.html",
     "unknown (needs page fetch)",
     "team_opponent_stats",
     "All-time franchise opponent totals across every season.",
     "Trivial table scrape.",
     3),
    ("franchise_year_by_year_opp_per_game", "Team", "P2_new", "allowed",
     "/teams/{ID}/opp_stats_per_game_totals.html",
     "https://www.basketball-reference.com/teams/ATL/opp_stats_per_game_totals.html",
     "unknown (needs page fetch)",
     "team_opponent_stats",
     "All-time franchise opponent per-game averages across every season.",
     "Trivial table scrape.",
     4),
    ("franchise_year_by_year_ranks", "Team", "P2_new", "allowed",
     "/teams/{ID}/stats_{basic,per_game,opp_basic,opp_per_game}_ranks.html",
     "https://www.basketball-reference.com/teams/ATL/stats_basic_ranks.html",
     "unknown (needs page fetch)",
     "",
     "Year-by-year league ranks for franchise (4 URL variants: basic, per_game, opp_basic, opp_per_game).",
     "Trivial table scrape; one row per season with rank columns.",
     5),
    ("franchise_year_over_year", "Team", "P2_new", "allowed",
     "/teams/{ID}/stats_{basic,per_game,opp_basic,opp_per_game}_yr_yr.html",
     "https://www.basketball-reference.com/teams/ATL/stats_basic_yr_yr.html",
     "unknown (needs page fetch)",
     "",
     "Year-over-year delta stats for franchise (4 URL variants).",
     "Trivial table scrape; deltas per season.",
     6),
    ("franchise_season_leaders", "Team", "P2_new", "allowed",
     "/teams/{ID}/leaders_season.html",
     "https://www.basketball-reference.com/teams/ATL/leaders_season.html",
     "unknown (needs page fetch)",
     "season_leaders",
     "Per-stat season leaders scoped to a single franchise (game, season, career rows).",
     "Trivial table scrape; multi-table page with per-stat sections.",
     7),
    ("franchise_career_leaders", "Team", "P2_new", "allowed",
     "/teams/{ID}/leaders_career.html",
     "https://www.basketball-reference.com/teams/ATL/leaders_career.html",
     "unknown (needs page fetch)",
     "career_leaders",
     "Per-stat career leaders scoped to a single franchise.",
     "Trivial table scrape; multi-table page with per-stat sections.",
     8),
    ("franchise_all_time_roster", "Team", "P2_new", "allowed",
     "/teams/{ID}/players.html",
     "https://www.basketball-reference.com/teams/ATL/players.html",
     "unknown (needs page fetch)",
     "team_roster",
     "Every player to ever play for the franchise.",
     "Trivial table scrape; distinct from per-season team_roster.",
     9),
    ("franchise_all_time_coaches", "Team", "P2_new", "allowed",
     "/teams/{ID}/coaches.html",
     "https://www.basketball-reference.com/teams/ATL/coaches.html",
     "unknown (needs page fetch)",
     "",
     "All-time franchise head coaches list.",
     "Trivial table scrape.",
     10),
    ("franchise_all_time_executives", "Team", "P2_new", "allowed",
     "/teams/{ID}/executives.html",
     "https://www.basketball-reference.com/teams/ATL/executives.html",
     "unknown (needs page fetch)",
     "",
     "All-time franchise GMs / executives.",
     "Trivial table scrape.",
     11),
    ("franchise_all_star_selections", "Team", "P2_new", "allowed",
     "/teams/{ID}/all_star.html",
     "https://www.basketball-reference.com/teams/ATL/all_star.html",
     "unknown (needs page fetch)",
     "player_all_star",
     "Every All-Star selection for franchise players.",
     "Trivial table scrape.",
     12),
    ("franchise_hall_of_famers", "Team", "P2_new", "allowed",
     "/teams/{ID}/hof.html",
     "https://www.basketball-reference.com/teams/ATL/hof.html",
     "unknown (needs page fetch)",
     "",
     "Hall-of-Famers who played for the franchise.",
     "Trivial table scrape.",
     13),
    ("franchise_uniform_numbers", "Team", "P2_new", "allowed",
     "/teams/{ID}/numbers.html",
     "https://www.basketball-reference.com/teams/ATL/numbers.html",
     "unknown (needs page fetch)",
     "league_uniform_numbers",
     "All uniform numbers retired/worn by franchise.",
     "Trivial table scrape.",
     14),
    ("franchise_head_to_head", "Team", "P2_new", "allowed",
     "/teams/{ID}/head2head.html",
     "https://www.basketball-reference.com/teams/ATL/head2head.html",
     "unknown (needs page fetch)",
     "",
     "Win-loss record vs every opponent franchise has ever faced.",
     "Trivial table scrape.",
     15),
    ("team_starting_lineups_depth", "Team", "P1_duplicate", "allowed",
     "/teams/{ID}/{YEAR}_start.html, /{YEAR}_depth.html",
     "https://www.basketball-reference.com/teams/BOS/2026_start.html",
     "unknown (needs page fetch)",
     "team_starting_lineups",
     "Per-season depth chart (5-man unit list is already covered by team_starting_lineups).",
     "Distinct parser from team_starting_lineups; would be a new endpoint.",
     16),
    ("team_referees", "Team", "P2_new", "allowed",
     "/teams/{ID}/{YEAR}_referees.html",
     "https://www.basketball-reference.com/teams/BOS/2026_referees.html",
     "unknown (needs page fetch)",
     "",
     "Per-game referee crews for a team's season.",
     "Likely one table; per-game rows with refs and crew position.",
     17),
    # ── People pages (18-20) ──
    ("coaches", "People", "P2_new", "allowed",
     "/coaches/{ID}c.html",
     "https://www.basketball-reference.com/coaches/mazzujo99c.html",
     "all_coach-stats, all_coach-awards, all_coach-of-the-year-voting",
     "",
     "Coach profile page: stats, awards, COY voting history.",
     "Bespoke multi-table page; comment-wrapped anchors require commented_table_id handling.",
     18),
    ("executives", "People", "P2_new", "allowed",
     "/executives/{ID}x.html",
     "https://www.basketball-reference.com/executives/stevebr99x.html",
     "unknown (needs page fetch)",
     "",
     "GM/executive profile page mirroring coach layout.",
     "Bespoke multi-table page; mirror coaches parser.",
     19),
    ("referees", "People", "P2_new", "allowed",
     "/referees/{ID}r.html",
     "https://www.basketball-reference.com/referees/kirklco99r.html",
     "unknown (needs page fetch)",
     "",
     "Referee profile page.",
     "Bespoke multi-table page; mirror coaches parser.",
     20),
    # ── Boxscore drilldowns (21-24) ──
    ("boxscore_pbp", "Boxscore", "P1_duplicate", "allowed",
     "/boxscores/pbp/{YYYYMMDD}{AWAY}.html",
     "https://www.basketball-reference.com/boxscores/pbp/202606100NYK.html",
     "pbp",
     "play_by_play",
     "Per-game play-by-play view (same URL pattern as existing play_by_play).",
     "Already covered; no action.",
     21),
    ("boxscore_shot_chart", "Boxscore", "P2_new", "allowed",
     "/boxscores/shot-chart/{YYYYMMDD}{AWAY}.html",
     "https://www.basketball-reference.com/boxscores/shot-chart/202606100NYK.html",
     "unknown (SVG + tables)",
     "player_shot_charts",
     "Per-game shot chart detail with SVG + embedded shot tables.",
     "Bespoke SVG+table; non-trivial parser.",
     22),
    ("boxscore_plus_minus", "Boxscore", "P2_new", "allowed",
     "/boxscores/plus-minus/{YYYYMMDD}{AWAY}.html",
     "https://www.basketball-reference.com/boxscores/plus-minus/202606100NYK.html",
     "box-{TEAM}-game-basic",
     "team_on_off",
     "Per-game on-court plus/minus detail.",
     "Reuses the box-TEAM-game-basic table shape.",
     23),
    ("boxscore_four_factors", "Boxscore", "P2_new", "allowed",
     "/boxscores/{YYYYMMDD}{AWAY}.html#all_four_factors",
     "https://www.basketball-reference.com/boxscores/202606100NYK.html#all_four_factors",
     "all_four_factors",
     "team_misc_four_factors",
     "Four-factors section of the standard boxscore (anchor-scoped extract).",
     "Same as boxscore URL but anchor-scoped; parser must extract by anchor id.",
     24),
    # ── Playoff year hub pages (25-33) ──
    ("playoff_year_index", "Playoffs", "P1_duplicate", "allowed",
     "/playoffs/NBA_{YEAR}.html",
     "https://www.basketball-reference.com/playoffs/NBA_2026.html",
     "all_playoffs",
     "playoff_bracket",
     "Season-level playoff hub (same URL as existing playoff_bracket).",
     "Already covered; no action.",
     25),
    ("playoff_year_standings", "Playoffs", "P2_new", "allowed",
     "/playoffs/NBA_{YEAR}_standings.html",
     "https://www.basketball-reference.com/playoffs/NBA_2026_standings.html",
     "standings (suspected)",
     "standings",
     "Postseason-seeded standings table.",
     "Trivial table scrape; id unconfirmed, needs page fetch.",
     26),
    ("playoff_year_games", "Playoffs", "P2_new", "allowed",
     "/playoffs/NBA_{YEAR}_games.html",
     "https://www.basketball-reference.com/playoffs/NBA_2026_games.html",
     "games (suspected)",
     "season_schedule",
     "Postseason-only schedule table.",
     "Trivial table scrape; id unconfirmed, needs page fetch.",
     27),
    ("playoff_year_leaders", "Playoffs", "P2_new", "allowed",
     "/playoffs/NBA_{YEAR}_leaders.html",
     "https://www.basketball-reference.com/playoffs/NBA_2026_leaders.html",
     "multiple (per-stat)",
     "season_leaders",
     "Postseason-only stat leader boards.",
     "Trivial table scrape; multi-table per stat.",
     28),
    ("playoff_year_player_totals", "Playoffs", "P2_new", "allowed",
     "/playoffs/NBA_{YEAR}_totals.html",
     "https://www.basketball-reference.com/playoffs/NBA_2026_totals.html",
     "unknown (needs page fetch)",
     "players_season_totals",
     "League-wide postseason player totals.",
     "Trivial table scrape; id unconfirmed, needs page fetch.",
     29),
    ("playoff_year_player_per_game", "Playoffs", "P2_new", "allowed",
     "/playoffs/NBA_{YEAR}_per_game.html",
     "https://www.basketball-reference.com/playoffs/NBA_2026_per_game.html",
     "unknown (needs page fetch)",
     "league_per_game_stats",
     "League-wide postseason player per-game averages.",
     "Trivial table scrape.",
     30),
    ("playoff_year_player_per_minute", "Playoffs", "P2_new", "allowed",
     "/playoffs/NBA_{YEAR}_per_minute.html",
     "https://www.basketball-reference.com/playoffs/NBA_2026_per_minute.html",
     "unknown (needs page fetch)",
     "league_per_36_minutes",
     "League-wide postseason player per-36 minutes.",
     "Trivial table scrape.",
     31),
    ("playoff_year_player_per_poss", "Playoffs", "P2_new", "allowed",
     "/playoffs/NBA_{YEAR}_per_poss.html",
     "https://www.basketball-reference.com/playoffs/NBA_2026_per_poss.html",
     "unknown (needs page fetch)",
     "league_per_100_possessions",
     "League-wide postseason player per-100-possessions.",
     "Trivial table scrape.",
     32),
    ("playoff_year_player_advanced", "Playoffs", "P2_new", "allowed",
     "/playoffs/NBA_{YEAR}_advanced.html",
     "https://www.basketball-reference.com/playoffs/NBA_2026_advanced.html",
     "unknown (needs page fetch)",
     "players_advanced_season_totals",
     "League-wide postseason player advanced stats.",
     "Trivial table scrape.",
     33),
    ("playoff_series_matchup", "Playoffs", "P2_new", "allowed",
     "/playoffs/{YEAR}-nba-{ROUND}-{TEAM_A}-vs-{TEAM_B}.html",
     "https://www.basketball-reference.com/playoffs/2026-nba-eastern-conference-first-round-76ers-vs-celtics.html",
     "all_other_scores, all_all_playoffs, all_four_factors, all_PHI, all_PHIadvanced, all_BOS, all_BOSadvanced",
     "",
     "Per-series page: schedule, four-factors, both teams' basic+advanced box totals.",
     "Bespoke multi-anchor page; could be split into 4-5 individual scrape endpoints.",
     34),
    # ── Awards (35-36) ──
    ("season_awards_voting", "Awards", "P1_duplicate", "allowed",
     "/awards/awards_{YEAR}.html",
     "https://www.basketball-reference.com/awards/awards_2025.html",
     "all_mvp, all_roy, all_dpoy, all_smoy, all_mip, all_clutch_poy, all_coy, all_leading_all_nba, all_leading_all_defense, all_leading_all_rookie",
     "season_awards",
     "Per-season vote tables for every award; full vote counts (existing season_awards covers winners-only summary).",
     "Same page, parser could be extended to surface all_* anchors.",
     35),
    ("awards_index", "Awards", "P2_new", "allowed",
     "/awards/{slug}.html",
     "https://www.basketball-reference.com/awards/mvp.html",
     "one <table> per slug",
     "season_awards",
     "Large family: per-award career index pages (mvp, roy, dpoy, smoy, mip, coy, all_league, all_defense, all_rookie, etc.). ~50+ slugs; one <table> per page.",
     "Trivial table scrape family; recommend picking a curated subset (mvp/roy/dpoy/smoy/mip/coy/all_league/all_defense/all_rookie).",
     36),
    # ── All-Star (37-45) ──
    ("allstar_game_index", "All-Star", "P2_new", "allowed",
     "/allstar/NBA_{YEAR}.html",
     "https://www.basketball-reference.com/allstar/NBA_2025.html",
     "per-team box tables",
     "player_all_star",
     "Per-game All-Star box score (pre-2025 format).",
     "Bespoke multi-table page (one per team).",
     37),
    ("allstar_game_boxscore", "All-Star", "P2_new", "allowed",
     "/allstar/{YYYYMMDD}{GAME_CODE}.html",
     "https://www.basketball-reference.com/allstar/202502162NBA.html",
     "per-team box tables",
     "team_box_scores",
     "New (2025+) explicit All-Star game URL.",
     "Bespoke multi-table page; could reuse team_box_scores parser.",
     38),
    ("allstar_voting", "All-Star", "P2_new", "allowed",
     "/allstar/NBA_{YEAR}_voting.html",
     "https://www.basketball-reference.com/allstar/NBA_2025_voting.html",
     "unknown (per-conference/position)",
     "",
     "Fan/player/media voting for All-Star starters.",
     "Bespoke multi-table page.",
     39),
    ("allstar_single_game_leaders", "All-Star", "P2_new", "allowed",
     "/allstar/leaders_game.html",
     "https://www.basketball-reference.com/allstar/leaders_game.html",
     "unknown (needs page fetch)",
     "season_leaders",
     "Single-game All-Star record holders.",
     "Trivial table scrape; resembles season_leaders slice.",
     40),
    ("allstar_career_leaders", "All-Star", "P2_new", "allowed",
     "/allstar/leaders_career.html",
     "https://www.basketball-reference.com/allstar/leaders_career.html",
     "unknown (needs page fetch)",
     "career_leaders",
     "Career All-Star stat leaders.",
     "Trivial table scrape.",
     41),
    ("allstar_career_stats", "All-Star", "P2_new", "allowed",
     "/allstar/NBA-allstar-career-stats.html",
     "https://www.basketball-reference.com/allstar/NBA-allstar-career-stats.html",
     "unknown (needs page fetch)",
     "player_all_star",
     "Every player with at least one All-Star selection, career All-Star numbers.",
     "Trivial table scrape; high-signal.",
     42),
    ("allstar_contests", "All-Star", "P2_new", "allowed",
     "/allstar/contest.html",
     "https://www.basketball-reference.com/allstar/contest.html",
     "unknown (needs page fetch)",
     "",
     "Dunk Contest / 3-Point Contest / Skills Challenge history.",
     "Bespoke page; non-tabular.",
     43),
    ("allstar_rookies", "All-Star", "P2_new", "allowed",
     "/allstar/rookie.html",
     "https://www.basketball-reference.com/allstar/rookie.html",
     "unknown (needs page fetch)",
     "rookie_stats",
     "Rising Stars Challenge rosters and results.",
     "Bespoke page.",
     44),
    ("allstar_legends", "All-Star", "P2_new", "allowed",
     "/allstar/legends.html",
     "https://www.basketball-reference.com/allstar/legends.html",
     "unknown (needs page fetch)",
     "",
     "NBA Legends Game (Horace Grant trophy).",
     "Bespoke page.",
     45),
    # ── League (46-51) ──
    ("league_rookies", "League", "P2_new", "allowed",
     "/leagues/NBA_{YEAR}_rookies.html",
     "https://www.basketball-reference.com/leagues/NBA_2026_rookies.html",
     "rookies (suspected)",
     "rookie_stats",
     "Rookie debutants per season; alternate format from existing rookie_stats.",
     "Trivial table scrape; verify id matches existing rookies table.",
     46),
    ("league_ratings", "League", "P2_new", "allowed",
     "/leagues/NBA_{YEAR}_ratings.html",
     "https://www.basketball-reference.com/leagues/NBA_2026_ratings.html",
     "unknown (multiple anchor tables: SRS, ORtg, DRtg, Pythagorean, SoS)",
     "",
     "Team SRS, ORtg/DRtg, Pythagorean, Strength-of-Schedule per season.",
     "Bespoke multi-table page with several anchor tables.",
     47),
    ("league_uniform_numbers", "League", "P2_new", "allowed",
     "/leagues/NBA_{YEAR}_numbers.html",
     "https://www.basketball-reference.com/leagues/NBA_2026_numbers.html",
     "unknown (needs page fetch)",
     "",
     "League-wide uniform-number frequency per season.",
     "Trivial table scrape.",
     48),
    ("league_preseason_odds", "League", "P2_new", "allowed",
     "/leagues/NBA_{YEAR}_preseason_odds.html",
     "https://www.basketball-reference.com/leagues/NBA_2026_preseason_odds.html",
     "unknown (needs page fetch)",
     "",
     "Pre-season championship / playoff / win-total odds.",
     "Trivial table scrape.",
     49),
    ("league_best_worst_records", "League", "P2_new", "allowed",
     "/leagues/NBA_best_records.html, NBA_worst_records.html, NBA_stats_per_game.html",
     "https://www.basketball-reference.com/leagues/NBA_best_records.html",
     "unknown (needs page fetch)",
     "",
     "All-time franchise best/worst records, plus a 'stats per game' historical leaderboard.",
     "Trivial table scrape; 3 related pages.",
     50),
    ("league_aba_best_worst", "League", "P2_new", "allowed",
     "/leagues/ABA_best_records.html, ABA_worst_records.html, ABA_stats_per_game.html, ABA_wins.html",
     "https://www.basketball-reference.com/leagues/ABA_best_records.html",
     "unknown (needs page fetch)",
     "",
     "ABA equivalent of league_best_worst_records (pre-1977).",
     "Trivial table scrape; ABA is historical scope.",
     51),
    # ── Leaders (52-57) ──
    ("leaders_record_boards", "Leaders", "P2_new", "allowed",
     "/leaders/{STAT}_{VIEW}.html (~30 stats x 7-9 views)",
     "https://www.basketball-reference.com/leaders/pts_career.html",
     "single leader table per page",
     "career_leaders, season_leaders",
     "Large family: ~30 stats (g, mp, fg, fg2, fg3, ft, fta, orb, drb, trb, ast, stl, blk, tov, pf, pts, trp_dbl, ...) x views (season, career, active, progress, yearly, top_10, game, series, finals, _c, _p).",
     "Existing career_leaders and season_leaders cover only 2 views; remaining views are new endpoints each with their own table id.",
     52),
    ("leaders_franchise", "Leaders", "P2_new", "allowed",
     "/leaders/franchise.html",
     "https://www.basketball-reference.com/leaders/franchise.html",
     "unknown (needs page fetch)",
     "",
     "Franchise-level leaderboard.",
     "Trivial table scrape.",
     53),
    ("leaders_team_records", "Leaders", "P2_new", "allowed",
     "/leaders/team_{pts,ast,trb,...}_wins.html, team_post_*.html",
     "https://www.basketball-reference.com/leaders/team_wins.html",
     "unknown (needs page fetch)",
     "",
     "Team-level (rather than player) leaderboards.",
     "Trivial table scrape; many slugs.",
     54),
    ("leaders_player_anniversary", "Leaders", "P2_new", "allowed",
     "/leaders/player_{stat}.html, player_post_*.html",
     "https://www.basketball-reference.com/leaders/player_pts.html",
     "unknown (needs page fetch)",
     "season_leaders",
     "Player season-leaderboard pages; full-season (not top-N) view.",
     "Trivial table scrape; resembles season_leaders but exhaustive.",
     55),
    ("leaders_specialty_boards", "Leaders", "P2_new", "allowed",
     "/leaders/{hof_prob,nba_mvp_shares,game_score,50-point-game-most-times,quadruple-double-most-times,most_championships,most_franchises,most_times_{leading,top_3,top_5,top_10}}.html",
     "https://www.basketball-reference.com/leaders/hof_prob.html",
     "single table per page",
     "",
     "Quirky / specialty single-table leaderboards.",
     "Trivial table scrape family; each is a single <table>.",
     56),
    ("trailers", "Leaders", "P2_new", "allowed",
     "/trailers/{STAT}_{VIEW}.html, _p.html (playoffs)",
     "https://www.basketball-reference.com/trailers/per_season.html",
     "single leader table per page",
     "",
     "Newer slimmer set of all-time leaderboards (~30 stats x 5 views; same set suffixed _p for playoffs).",
     "Trivial table scrape family; mirrors leaders/ shape.",
     57),
    # ── Draft (58-63) ──
    ("draft_year", "Draft", "P1_duplicate", "allowed",
     "/draft/NBA_{YEAR}.html (and BAA_{YEAR} pre-1950)",
     "https://www.basketball-reference.com/draft/NBA_2025.html",
     "stats (suspected; one table per round plus aggregate)",
     "draft_picks",
     "Per-year draft board URL (same path as existing draft_picks endpoint).",
     "Already covered by draft_picks; no action.",
     58),
    ("draft_year_2_rounds", "Draft", "P2_new", "allowed",
     "/draft/BAA_{YEAR}.html (1947-1949)",
     "https://www.basketball-reference.com/draft/BAA_1947.html",
     "same as draft_picks stats",
     "draft_picks",
     "Pre-NBA BAA drafts; same table shape.",
     "Trivial table scrape; could extend draft_picks to accept BAA_ prefix.",
     59),
    ("draft_team_picks", "Draft", "P2_new", "allowed",
     "/teams/{ID}/draft.html",
     "https://www.basketball-reference.com/teams/ATL/draft.html",
     "unknown (needs page fetch)",
     "",
     "Every draft pick ever made by a franchise.",
     "Trivial table scrape.",
     60),
    ("draft_expansion", "Draft", "P2_new", "allowed",
     "/draft/NBA_{YEAR}_expansion.html",
     "https://www.basketball-reference.com/draft/NBA_2004_expansion.html",
     "unknown (needs page fetch)",
     "",
     "Expansion-draft picks.",
     "Trivial table scrape.",
     61),
    ("draft_rights", "Draft", "P2_new", "allowed",
     "/draft/draft_rights.html",
     "https://www.basketball-reference.com/draft/draft_rights.html",
     "unknown (needs page fetch)",
     "",
     "Outstanding draft rights (unsigned picks).",
     "Trivial table scrape.",
     62),
    ("draft_combined_college", "Draft", "P2_new", "allowed",
     "/friv/draft.fcgi?college={SLUG}",
     "https://www.basketball-reference.com/friv/draft.fcgi?college=duke",
     "unknown (needs page fetch)",
     "",
     "All players drafted from a specific college (query-driven).",
     "Trivial table scrape; consider a college_draft_alumni endpoint.",
     63),
    # ── Friv (64-77) ──
    ("friv_birthdays", "Friv", "P2_new", "allowed",
     "/friv/birthdays.fcgi?month={M}&day={D}",
     "https://www.basketball-reference.com/friv/birthdays.fcgi?month=12&day=30",
     "unknown (needs page fetch)",
     "",
     "All players born on a given date.",
     "Trivial table scrape; query-driven.",
     64),
    ("friv_birthyears", "Friv", "P2_new", "allowed",
     "/friv/birthyears.fcgi?year={Y}",
     "https://www.basketball-reference.com/friv/birthyears.fcgi?year=1984",
     "unknown (needs page fetch)",
     "",
     "All players born in a given year.",
     "Trivial table scrape; query-driven.",
     65),
    ("friv_birthplaces", "Friv", "P2_new", "allowed",
     "/friv/birthplaces.fcgi?country={CC}&state={S}",
     "https://www.basketball-reference.com/friv/birthplaces.fcgi?country=US&state=OH",
     "unknown (needs page fetch)",
     "",
     "All players from a given birthplace.",
     "Trivial table scrape; query-driven.",
     66),
    ("friv_high_schools", "Friv", "P2_new", "allowed",
     "/friv/high_schools.fcgi?country={CC}&state={S}",
     "https://www.basketball-reference.com/friv/high_schools.fcgi?country=US&state=OH",
     "unknown (needs page fetch)",
     "",
     "All players from a given state + high school.",
     "Trivial table scrape; query-driven.",
     67),
    ("friv_colleges", "Friv", "P2_new", "allowed",
     "/friv/colleges.fcgi?college={SLUG}",
     "https://www.basketball-reference.com/friv/colleges.fcgi?college=duke",
     "unknown (needs page fetch)",
     "",
     "All NBA players from a given college (alumni).",
     "Trivial table scrape; query-driven; overlaps draft_combined_college.",
     68),
    ("friv_uniform_numbers", "Friv", "P2_new", "allowed",
     "/friv/numbers.cgi?number={N}",
     "https://www.basketball-reference.com/friv/numbers.cgi?number=23",
     "unknown (needs page fetch)",
     "league_uniform_numbers",
     "Every player to ever wear a given uniform number.",
     "Trivial table scrape; query-driven.",
     69),
    ("friv_teammates_and_opponents", "Friv", "P2_new", "allowed",
     "/friv/teammates_and_opponents.fcgi?pid_select=...&pid={ID}&type={t|o}",
     "https://www.basketball-reference.com/friv/teammates_and_opponents.fcgi?pid_select=LeBron%20James&pid=jamesle01&idx=players&type=t",
     "unknown (needs page fetch)",
     "",
     "Player's teammates (type=t) and opponents (type=o).",
     "Trivial table scrape; query-driven.",
     70),
    ("friv_daily_leaders", "Friv", "P2_new", "allowed",
     "/friv/dailyleaders.fcgi",
     "https://www.basketball-reference.com/friv/dailyleaders.fcgi",
     "unknown (needs page fetch)",
     "",
     "Single-day stat-leader board.",
     "Trivial table scrape.",
     71),
    ("friv_milestones", "Friv", "P2_new", "allowed",
     "/friv/milestones.fcgi",
     "https://www.basketball-reference.com/friv/milestones.fcgi",
     "unknown (needs page fetch)",
     "",
     "Upcoming career milestones.",
     "Trivial table scrape.",
     72),
    ("friv_mvp_tracker", "Friv", "P2_new", "allowed",
     "/friv/mvp.html",
     "https://www.basketball-reference.com/friv/mvp.html",
     "unknown (needs page fetch)",
     "season_awards",
     "In-season MVP tracker.",
     "Trivial table scrape; resembles season_awards but in-season.",
     73),
    ("friv_playoff_probabilities", "Friv", "P2_new", "allowed",
     "/friv/playoff_prob.html",
     "https://www.basketball-reference.com/friv/playoff_prob.html",
     "unknown (needs page fetch)",
     "",
     "In-season playoff-odds projections.",
     "Trivial table scrape.",
     74),
    ("friv_standings_on_date", "Friv", "P2_new", "allowed",
     "/friv/standings.fcgi",
     "https://www.basketball-reference.com/friv/standings.fcgi",
     "unknown (needs page fetch)",
     "standings_by_date",
     "Standings as of any historical date.",
     "Trivial table scrape; query-driven; overlaps standings_by_date.",
     75),
    ("friv_projected_draft", "Friv", "P2_new", "allowed",
     "/friv/proj_draft.html",
     "https://www.basketball-reference.com/friv/proj_draft.html",
     "unknown (needs page fetch)",
     "",
     "Mock/project draft order.",
     "Trivial table scrape.",
     76),
    ("player_high_school_exhibition", "Player", "P2_new", "allowed",
     "/players/{L}/{ID}/{slug}-high-school-amateur-exhibition.html",
     "https://www.basketball-reference.com/players/j/jamesle01/lebron-high-school-amateur-exhibition.html",
     "unknown (needs page fetch)",
     "",
     "Sub-page for pre-NBA / high-school exhibition stats (e.g. LeBron's senior year).",
     "Bespoke page.",
     77),
    # ── Player pages with restricted or no-stats content (78) ──
    ("player_news", "Player", "off_domain", "allowed",
     "/players/news.fcgi?id={ID}",
     "https://www.basketball-reference.com/players/news.fcgi?id=jamesle01",
     "(news feed list, not a stats table)",
     "",
     "Player newsfeed-style page; not a tabular stats endpoint.",
     "Not stats; skip for stats pipeline.",
     78),
    # ── Disallowed by robots.txt (79-87) ──
    ("player_gamelog", "Player", "P1_duplicate", "disallowed",
     "/players/{L}/{ID}/gamelog/{YEAR}/, /gamelog-playoffs/",
     "https://www.basketball-reference.com/players/j/jamesle01/gamelog/2024/",
     "unknown (per-game table per season)",
     "regular_season_player_box_scores, playoff_player_box_scores",
     "Per-player/per-season gamelog page.",
     "Disallowed by robots (Disallow: */gamelog/); same data is reachable via existing regular_season_player_box_scores and playoff_player_box_scores.",
     79),
    ("player_splits", "Player", "P1_duplicate", "disallowed",
     "/players/{L}/{ID}/splits/{YEAR}/, /splits/",
     "https://www.basketball-reference.com/players/j/jamesle01/splits/2024/",
     "splits",
     "player_splits",
     "Player splits by month/position/etc (existing player_splits already models this).",
     "Disallowed by robots; existing endpoint already covers via same path.",
     80),
    ("player_shooting", "Player", "P1_duplicate", "disallowed",
     "/players/{L}/{ID}/shooting/{YEAR}/",
     "https://www.basketball-reference.com/players/j/jamesle01/shooting/2024/",
     "shooting",
     "player_shot_charts",
     "Player shot-location detail (existing player_shot_charts already models this).",
     "Disallowed by robots; existing endpoint already covers via same path.",
     81),
    ("player_lineups", "Player", "P2_disallowed", "disallowed",
     "/players/{L}/{ID}/lineups/{YEAR}/",
     "https://www.basketball-reference.com/players/j/jamesle01/lineups/2024/",
     "unknown (needs page fetch)",
     "team_lineups",
     "Per-player lineup combos played with.",
     "Disallowed by robots (Disallow: */lineups/); no existing endpoint for player-specific lineups.",
     82),
    ("player_on_off", "Player", "P1_duplicate", "disallowed",
     "/players/{L}/{ID}/on-off/{YEAR}/",
     "https://www.basketball-reference.com/players/j/jamesle01/on-off/2024/",
     "on-off",
     "player_on_off",
     "Player on-court / off-court splits (existing player_on_off already models this).",
     "Disallowed by robots; existing endpoint already covers via same path.",
     83),
    ("team_gamelog", "Team", "P2_disallowed", "disallowed",
     "/teams/{ID}/{YEAR}/gamelog/",
     "https://www.basketball-reference.com/teams/BOS/2026/gamelog/",
     "unknown (per-game table)",
     "",
     "Team per-game log for a season.",
     "Disallowed by robots (Disallow: */gamelog/); team_box_scores already covers same data via /boxscores/.",
     84),
    ("team_splits", "Team", "P1_duplicate", "disallowed",
     "/teams/{ID}/{YEAR}/splits/",
     "https://www.basketball-reference.com/teams/BOS/2026/splits/",
     "team_splits",
     "team_splits",
     "Team season splits (existing team_splits already models this).",
     "Disallowed by robots; existing endpoint already covers via same path.",
     85),
    ("team_lineups", "Team", "P1_duplicate", "disallowed",
     "/teams/{ID}/{YEAR}/lineups/",
     "https://www.basketball-reference.com/teams/BOS/2026/lineups/",
     "lineups_5-man_ (suspected)",
     "team_lineups",
     "Team lineup combos for a season (existing team_lineups already models this).",
     "Disallowed by robots; existing endpoint already covers via same path.",
     86),
    ("team_on_off", "Team", "P1_duplicate", "disallowed",
     "/teams/{ID}/{YEAR}/on-off/",
     "https://www.basketball-reference.com/teams/BOS/2026/on-off/",
     "on_off (suspected)",
     "team_on_off",
     "Team on/off-court detail (existing team_on_off already models this).",
     "Disallowed by robots; existing endpoint already covers via same path.",
     87),
    # ── Off-domain (88-90) ──
    ("stathead_player_season_finder", "Stathead", "off_domain", "off_domain",
     "https://www.sports-reference.com/stathead/basketball/player-season-finder.cgi",
     "https://www.sports-reference.com/stathead/basketball/player-season-finder.cgi",
     "(form-result table)",
     "",
     "Cross-domain Stathead query interface.",
     "Off-domain (sports-reference.com); premium / form-driven; skip.",
     88),
    ("stathead_player_game_finder", "Stathead", "off_domain", "off_domain",
     "https://www.sports-reference.com/stathead/basketball/player-game-finder.cgi",
     "https://www.sports-reference.com/stathead/basketball/player-game-finder.cgi",
     "unknown (form-driven)",
     "",
     "Stathead player game finder.",
     "Off-domain; paywalled; skip.",
     89),
    ("stathead_finder_family", "Stathead", "off_domain", "off_domain",
     "https://www.sports-reference.com/stathead/basketball/{player-game,player-season,player-streak,player-span,team-season,team-game,team-streak,team-span,event,shot,quarter,versus,shuttle,pcm}-finder.cgi",
     "https://www.sports-reference.com/stathead/basketball/pcm-finder.cgi",
     "unknown (form-driven)",
     "",
     "All Stathead finders (12+ variants).",
     "Off-domain; behind login/paywall; disallowed by robots (/play-index/*.cgi?*).",
     90),

    # ── Audit pass 2: /friv/ deep crawl + missed league URLs (99-126) ──
    ("friv_players_who_played_for_multiple_teams", "Friv", "P2_new", "allowed",
     "/friv/players-who-played-for-multiple-teams-franchises.fcgi",
     "https://www.basketball-reference.com/friv/players-who-played-for-multiple-teams-franchises.fcgi",
     "unknown (needs page fetch)",
     "",
     "Query form: every player who played for two specified franchises (e.g. DAL+SA). High-value 'Find a trade partner' tool.",
     "Single page fetch + parse of result table; two-franchise query is part of URL string.",
     99),
    ("friv_buzzer_beaters", "Friv", "P2_new", "allowed",
     "/friv/buzzer-beaters.html",
     "https://www.basketball-reference.com/friv/buzzer-beaters.html",
     "unknown (needs page fetch)",
     "",
     "Curated list of last-second game-winning shots.",
     "Trivial table scrape.",
     100),
    ("friv_coffee", "Friv", "P2_new", "allowed",
     "/friv/coffee.fcgi",
     "https://www.basketball-reference.com/friv/coffee.fcgi",
     "unknown (needs page fetch)",
     "",
     "Random coffee-cup-shaped trivia. Low value.",
     "Trivial; not stats - flag as low value.",
     101),
    ("friv_east_vs_west", "Friv", "P2_new", "allowed",
     "/friv/east_vs_west.html",
     "https://www.basketball-reference.com/friv/east_vs_west.html",
     "unknown (needs page fetch)",
     "",
     "Inter-conference all-time head-to-head record (East vs West + W-L splits).",
     "Trivial table scrape.",
     102),
    ("friv_hof_index", "Friv", "P2_new", "allowed",
     "/friv/hof.fcgi",
     "https://www.basketball-reference.com/friv/hof.fcgi",
     "unknown (needs page fetch)",
     "franchise_hall_of_famers",
     "League-wide HoFer index (master list of every NBA/ABA inductee); distinct from per-franchise hof.html.",
     "Trivial table scrape.",
     103),
    ("friv_league_injuries", "Friv", "P2_new", "allowed",
     "/friv/injuries.fcgi",
     "https://www.basketball-reference.com/friv/injuries.fcgi",
     "unknown (needs page fetch)",
     "team_injury_report",
     "League-wide current injury report (one table across all teams); distinct URL/format from per-team pages.",
     "Trivial table scrape.",
     104),
    ("friv_last_n_days", "Friv", "P2_new", "allowed",
     "/friv/last_n_days.fcgi?n={N}",
     "https://www.basketball-reference.com/friv/last_n_days.fcgi?n=10",
     "unknown (needs page fetch)",
     "season_leaders",
     "Last-N-day league leaders per stat (N is a URL parameter).",
     "Trivial table scrape; parameterized.",
     105),
    ("friv_upcoming_milestones", "Friv", "P1_duplicate", "allowed",
     "/friv/upcoming-milestones.html",
     "https://www.basketball-reference.com/friv/upcoming-milestones.html",
     "unknown (needs page fetch)",
     "friv_milestones",
     "Upcoming career milestones (HTML flavor; friv_milestones is the .fcgi). Same data, different renderer.",
     "Likely duplicate of friv_milestones; verify before adding endpoint.",
     106),
    ("friv_franchise_milestones", "Friv", "P2_new", "allowed",
     "/friv/franchise_milestones.fcgi",
     "https://www.basketball-reference.com/friv/franchise_milestones.fcgi",
     "unknown (needs page fetch)",
     "",
     "Upcoming franchise milestones (wins, points, etc.) scoped to each team.",
     "Trivial table scrape.",
     107),
    ("friv_most_g_no_playoffs", "Friv", "P2_new", "allowed",
     "/friv/most_g_no_playoffs.html",
     "https://www.basketball-reference.com/friv/most_g_no_playoffs.html",
     "unknown (needs page fetch)",
     "",
     "Single-table trivia: players with most games without ever making the playoffs.",
     "Trivial table scrape.",
     108),
    ("friv_on_this_date", "Friv", "P2_new", "allowed",
     "/friv/on_this_date.fcgi",
     "https://www.basketball-reference.com/friv/on_this_date.fcgi",
     "unknown (needs page fetch)",
     "",
     "'On this day in NBA history' - historical events/games/births/deaths for any given date.",
     "Trivial; date-parameterized.",
     109),
    ("friv_7_game_playoff_series_outcomes", "Friv", "P2_new", "allowed",
     "/friv/7-game-playoff-series-outcomes.html",
     "https://www.basketball-reference.com/friv/7-game-playoff-series-outcomes.html",
     "unknown (needs page fetch)",
     "",
     "Historical 7-game series win/loss outcomes - breakdown by which team won each game 1-7.",
     "Trivial table scrape.",
     110),
    ("friv_continuity", "Friv", "P2_new", "allowed",
     "/friv/continuity.html",
     "https://www.basketball-reference.com/friv/continuity.html",
     "unknown (needs page fetch)",
     "leaders_record_boards",
     "Annual roster-continuity leaders (most returning minutes). High-quality analytics leaderboard.",
     "Trivial table scrape.",
     111),
    ("friv_projections", "Friv", "P2_new", "allowed",
     "/friv/projections.cgi",
     "https://www.basketball-reference.com/friv/projections.cgi",
     "unknown (needs page fetch)",
     "",
     "Standings / playoff odds projections (custom).",
     "Trivial; low value, skip if not stats.",
     112),
    ("friv_trades", "Friv", "P2_new", "allowed",
     "/friv/trades.fcgi",
     "https://www.basketball-reference.com/friv/trades.fcgi",
     "unknown (needs page fetch)",
     "team_transactions",
     "League-wide trade history; cleaner than the per-team team_transactions variant.",
     "Trivial table scrape.",
     113),
    ("friv_numbers_index", "Friv", "P2_new", "allowed",
     "/friv/numbers.fcgi",
     "https://www.basketball-reference.com/friv/numbers.fcgi",
     "unknown (needs page fetch)",
     "friv_uniform_numbers",
     "League-wide uniform-numbers overview/index page (distinct from the per-number .cgi form in friv_uniform_numbers).",
     "Trivial table scrape.",
     114),
    ("friv_transactions", "Friv", "P2_new", "allowed",
     "/friv/transactions.fcgi",
     "https://www.basketball-reference.com/friv/transactions.fcgi",
     "unknown (needs page fetch)",
     "team_transactions",
     "League-wide transactions index; distinct URL from per-team /{ID}_transactions.html.",
     "Trivial table scrape.",
     115),
    ("league_player_advanced", "League", "P1_duplicate", "allowed",
     "/leagues/NBA_{YEAR}_advanced.html",
     "https://www.basketball-reference.com/leagues/NBA_2026_advanced.html",
     "div_advanced_stats (suspected)",
     "players_advanced_season_totals",
     "League-wide player advanced stats. SAME URL as existing players_advanced_season_totals endpoint - rediscovered in audit.",
     "Already covered by players_advanced_season_totals; no action.",
     116),
    ("league_player_totals", "League", "P1_duplicate", "allowed",
     "/leagues/NBA_{YEAR}_totals.html",
     "https://www.basketball-reference.com/leagues/NBA_2026_totals.html",
     "one large table",
     "league_totals, players_season_totals",
     "League-wide player totals as standalone URL. SAME URL as existing league_totals/players_season_totals.",
     "Already covered; no action.",
     117),
    ("league_standings_by_date_conference", "Standings", "P1_duplicate", "allowed",
     "/leagues/NBA_{YEAR}_standings_by_date_{eastern,western}_conference.html",
     "https://www.basketball-reference.com/leagues/NBA_1980_standings_by_date_eastern_conference.html",
     "unknown (needs page fetch)",
     "standings_by_date",
     "Conference-scoped variant of standings_by_date. SAME URL pattern as existing endpoint.",
     "Already covered by standings_by_date; no action.",
     119),
    ("league_season_games_by_month", "League", "P1_duplicate", "allowed",
     "/leagues/NBA_{YEAR}_games-{month}.html",
     "https://www.basketball-reference.com/leagues/NBA_2026_games-june.html",
     "unknown (needs page fetch)",
     "season_schedule",
     "Per-month schedule breakdown. Already fetched dynamically by _build_season_schedule_example.",
     "Already covered by season_schedule; no action.",
     120),
    ("league_rookies_per_season_detail", "League", "P2_new", "allowed",
     "/leagues/NBA_{YEAR}_rookies-season-stats.html",
     "https://www.basketball-reference.com/leagues/NBA_2006_rookies-season-stats.html",
     "unknown (needs page fetch)",
     "league_rookies, rookie_stats",
     "Per-season rookies DETAIL page (vs rookies.html which is a debut-list). Different URL, different content.",
     "Trivial table scrape.",
     121),
    ("awards_player_of_the_seeding_games", "Awards", "P2_new", "allowed",
     "/awards/player_of_the_seeding_games.html",
     "https://www.basketball-reference.com/awards/player_of_the_seeding_games.html",
     "unknown (needs page fetch)",
     "awards_index",
     "Standalone index for the 2020 seeding-games Player of the Year award. Missed from awards_index enumeration in pass 1.",
     "Trivial table scrape.",
     122),
    ("playoff_historical_series_index", "Playoffs", "P2_new", "allowed",
     "/playoffs/series.html",
     "https://www.basketball-reference.com/playoffs/series.html",
     "one large table of all-time series",
     "playoff_year_index",
     "Every playoff series ever played, all-time, on one page. Distinct from /playoffs/ (champions) and per-year pages.",
     "Trivial table scrape.",
     123),
    ("executives_register", "People", "P2_new", "allowed",
     "/executives/NBA_stats.html",
     "https://www.basketball-reference.com/executives/NBA_stats.html",
     "unknown (needs page fetch)",
     "executives",
     "League-wide executive register - index of all NBA executives/coaches. Distinct from individual /executives/{ID}x.html.",
     "Trivial table scrape.",
     124),
    ("bbr_blog", "Content", "off_domain", "allowed",
     "/bbr-blog/{YYYY}/{MM}/{slug}/",
     "https://www.basketball-reference.com/bbr-blog/2024/11/best-nba-teams-of-all-time-part-two/",
     "n/a (article, not stats)",
     "",
     "Long-form editorial articles. Not a stats page - flag only.",
     "Non-stats; skip for stats pipeline.",
     125),
    ("rand", "Tool", "off_domain", "allowed",
     "/rand.fcgi",
     "https://www.basketball-reference.com/rand.fcgi",
     "n/a",
     "",
     "Random-article redirector. Not a stats page.",
     "Non-stats; skip.",
     126),
]

# ── Adjacent domains flagged-only (Table 2) ──
ADJACENT_DOMAINS: list[tuple[str, str, str, str, str, str, str, str, str, str, int]] = [
    ("cbb_college", "Adjacent", "off_domain", "off_domain",
     "sports-reference.com/cbb",
     "https://www.sports-reference.com/cbb/players/",
     "(same table conventions as BREF, no NBA men)",
     "",
     "College basketball; mirrors BREF URL structure but NBA scope only.",
     "Out of scope; flagged.",
     91),
    ("wnba", "Adjacent", "off_domain", "off_domain",
     "basketball-reference.com/wnba",
     "https://www.basketball-reference.com/wnba/years/{Y}.html",
     "(per-stat table per page)",
     "",
     "WNBA; mirrors NBA URL structure exactly.",
     "Out of scope; flagged.",
     92),
    ("gleague", "Adjacent", "off_domain", "off_domain",
     "basketball-reference.com/gleague",
     "https://www.basketball-reference.com/gleague/players/",
     "(landing page only)",
     "",
     "NBA G-League players index; minimal per-season data.",
     "Out of scope; flagged.",
     93),
    ("international", "Adjacent", "off_domain", "off_domain",
     "basketball-reference.com/international",
     "https://www.basketball-reference.com/international/teams/{slug}/{Y}.html",
     "(per-team season table)",
     "",
     "Non-NBA international leagues (~200 clubs across ~15 leagues).",
     "Out of scope; flagged.",
     94),
    ("mens_olympics", "Adjacent", "off_domain", "off_domain",
     "basketball-reference.com/international/mens-olympics",
     "https://www.basketball-reference.com/international/mens-olympics/",
     "(tournament table)",
     "",
     "Olympic basketball (men).",
     "Out of scope; flagged.",
     95),
    ("womens_olympics", "Adjacent", "off_domain", "off_domain",
     "basketball-reference.com/international/womens-olympics",
     "https://www.basketball-reference.com/international/womens-olympics/",
     "(tournament table)",
     "",
     "Olympic basketball (women).",
     "Out of scope; flagged.",
     96),
    ("nbl_australia", "Adjacent", "off_domain", "off_domain",
     "basketball-reference.com/nbl",
     "https://www.basketball-reference.com/nbl/players/",
     "(landing page only)",
     "",
     "Australian NBL (historical players).",
     "Out of scope; flagged.",
     97),
    ("stathead_subscription", "Adjacent", "off_domain", "off_domain",
     "sports-reference.com/stathead/basketball",
     "https://www.sports-reference.com/stathead/basketball/",
     "(form-driven)",
     "",
     "Stathead subscription product; paywalled.",
     "Out of scope; flagged.",
     98),
]

COLUMNS: list[str] = [
    "page_family",
    "category",
    "tier",
    "robots_status",
    "canonical_pattern",
    "sample_url",
    "primary_table_id_s",
    "resembles_endpoint",
    "description",
    "parser_requirements",
    "librarian_row",
]


def write_csv(path: Path, rows: Sequence[Sequence[object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh, quoting=csv.QUOTE_MINIMAL)
        writer.writerow(COLUMNS)
        for row in rows:
            writer.writerow(row)


def main() -> int:
    all_rows = list(ROWS) + list(ADJACENT_DOMAINS)
    write_csv(OUTPUT_PATH, all_rows)

    by_tier: dict[str, int] = {}
    for row in all_rows:
        tier = str(row[2])
        by_tier[tier] = by_tier.get(tier, 0) + 1

    print(f"Wrote {len(all_rows)} rows to {OUTPUT_PATH}")
    print("Tier counts:")
    for tier, count in sorted(by_tier.items(), key=lambda kv: -kv[1]):
        print(f"  {tier}: {count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
