#!/usr/bin/env python3
"""Generate REFERENCE.md and docs/reference.md from the ENDPOINTS registry.

The registry is the single source of truth for endpoint metadata, so the
reference documentation is generated rather than hand-written. Run this after
adding or changing a registry entry:

    uv run python scripts/generate_reference.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from courtside_data import client  # noqa: E402
from courtside_data.endpoints import ENDPOINTS  # noqa: E402

# client submodule -> section heading, in display order
SECTIONS = {
    "courtside_data.client.league": "League",
    "courtside_data.client.playoffs": "Playoffs",
    "courtside_data.client.draft": "Draft, Awards, Leaders",
    "courtside_data.client.players": "Player",
    "courtside_data.client.teams": "Team",
    "courtside_data.client.games": "Box Scores, Schedule, Search",
}

HEADER = """\
# Endpoint Reference

<!-- Generated by scripts/generate_reference.py — do not edit by hand. -->

Every endpoint is callable three ways: as a module-level function
(`from courtside_data import client`), as a `CourtsideClient` method, or as a
CLI subcommand (`courtside-data <endpoint> --<param> <value>`).

All endpoints accept the standard output parameters `output_type`
(`OutputType.JSON`, `OutputType.CSV`, or `OutputType.DATAFRAME`),
`output_file_path`, `output_write_option`, and `json_options`.
"""


def _table_location(endpoint) -> str:
    if endpoint.custom:
        return "bespoke `HTTPService` method"
    parts = []
    if endpoint.table_id is not None:
        parts.append(f"`table#{endpoint.table_id}`")
    if endpoint.commented_table_id is not None:
        parts.append(f"commented `#{endpoint.commented_table_id}`")
    if endpoint.transaction_list_fallback:
        parts.append("transaction-list fallback")
    return ", ".join(parts) if parts else "—"


def _summary(name: str) -> str:
    doc = getattr(client, name).__doc__ or ""
    lines = [line.strip() for line in doc.strip().splitlines() if line.strip()]
    return lines[0] if lines else ""


def _endpoint_section(name: str, endpoint) -> str:
    lines = [f"### `{name}`", "", _summary(name), ""]
    params = ", ".join(f"`{p}`" for p in endpoint.params) or "—"
    lines.append(f"- **Parameters:** {params}")
    lines.append(f"- **URL:** `{endpoint.path}`")
    lines.append(f"- **Table:** {_table_location(endpoint)}")
    if endpoint.error is not None:
        codes = ", ".join(str(code) for code in endpoint.error_status_codes)
        lines.append(f"- **Raises:** `{endpoint.error.__name__}` on HTTP {codes}")
    if endpoint.csv_columns:
        columns = ", ".join(f"`{c}`" for c in endpoint.csv_columns)
        lines.append("")
        lines.append("<details><summary>CSV columns</summary>")
        lines.append("")
        lines.append(columns)
        lines.append("")
        lines.append("</details>")
    else:
        lines.append("- **CSV columns:** auto-detected from the response")
    lines.append("")
    return "\n".join(lines)


def render() -> str:
    by_section: dict[str, list[str]] = {title: [] for title in SECTIONS.values()}
    for name, endpoint in ENDPOINTS.items():
        module = getattr(client, name).__module__
        title = SECTIONS[module]
        by_section[title].append(_endpoint_section(name, endpoint))

    parts = [HEADER]
    for title, sections in by_section.items():
        parts.append(f"## {title}\n")
        parts.extend(sections)
    return "\n".join(parts)


def main() -> int:
    content = render()
    for target in (REPO_ROOT / "REFERENCE.md", REPO_ROOT / "docs" / "reference.md"):
        target.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {target.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
