"""Lookup dictionaries that map abbreviations to domain enum values."""

from courtside_data.domain.enums import (
    Conference,
    Division,
    League,
    Location,
    Outcome,
    Position,
    Team,
)

DIVISIONS_TO_CONFERENCES = {
    Division.ATLANTIC: Conference.EASTERN,
    Division.CENTRAL: Conference.EASTERN,
    Division.SOUTHEAST: Conference.EASTERN,
    Division.MIDWEST: Conference.WESTERN,
    Division.PACIFIC: Conference.WESTERN,
    Division.SOUTHWEST: Conference.WESTERN,
    Division.NORTHWEST: Conference.WESTERN,
}


TEAM_ABBREVIATIONS_TO_TEAM = {
    "ATL": Team.ATLANTA_HAWKS,
    "BOS": Team.BOSTON_CELTICS,
    "BRK": Team.BROOKLYN_NETS,
    "CHI": Team.CHICAGO_BULLS,
    "CHO": Team.CHARLOTTE_HORNETS,
    "CLE": Team.CLEVELAND_CAVALIERS,
    "DAL": Team.DALLAS_MAVERICKS,
    "DEN": Team.DENVER_NUGGETS,
    "DET": Team.DETROIT_PISTONS,
    "GSW": Team.GOLDEN_STATE_WARRIORS,
    "HOU": Team.HOUSTON_ROCKETS,
    "IND": Team.INDIANA_PACERS,
    "LAC": Team.LOS_ANGELES_CLIPPERS,
    "LAL": Team.LOS_ANGELES_LAKERS,
    "MEM": Team.MEMPHIS_GRIZZLIES,
    "MIA": Team.MIAMI_HEAT,
    "MIL": Team.MILWAUKEE_BUCKS,
    "MIN": Team.MINNESOTA_TIMBERWOLVES,
    "NOP": Team.NEW_ORLEANS_PELICANS,
    "NYK": Team.NEW_YORK_KNICKS,
    "OKC": Team.OKLAHOMA_CITY_THUNDER,
    "ORL": Team.ORLANDO_MAGIC,
    "PHI": Team.PHILADELPHIA_76ERS,
    "PHO": Team.PHOENIX_SUNS,
    "POR": Team.PORTLAND_TRAIL_BLAZERS,
    "SAC": Team.SACRAMENTO_KINGS,
    "SAS": Team.SAN_ANTONIO_SPURS,
    "TOR": Team.TORONTO_RAPTORS,
    "UTA": Team.UTAH_JAZZ,
    "WAS": Team.WASHINGTON_WIZARDS,
    # DEPRECATED TEAMS
    "BUF": Team.BUFFALO_BRAVES,
    # TODO: the 1963-73 Baltimore Bullets (Wizards lineage, abbreviated ``BAL``
    # by Basketball Reference) is a different franchise from the defunct BAA
    # Baltimore Bullets (``BLB``). They currently share the same name-based
    # enum ``Team.BALTIMORE_BULLETS``. A future franchise-era modelling pass
    # (consistent with the Kansas City → Sacramento Kings split) should add a
    # distinct enum for the Wizards-lineage Baltimore era so the two are not
    # conflated. The reverse map already pins the canonical abbreviation to
    # ``BLB`` to preserve existing serialisation behaviour.
    "BAL": Team.BALTIMORE_BULLETS,
    "CIN": Team.CINCINNATI_ROYALS,
    "KCK": Team.KANSAS_CITY_KINGS,
    "KCO": Team.KANSAS_CITY_OMAHA_KINGS,
    "NJN": Team.NEW_JERSEY_NETS,
    "NOH": Team.NEW_ORLEANS_HORNETS,
    "NOK": Team.NEW_ORLEANS_OKLAHOMA_CITY_HORNETS,
    "PHW": Team.PHILADELPHIA_WARRIORS,
    "SFW": Team.SAN_FRANCISCO_WARRIORS,
    "CHA": Team.CHARLOTTE_BOBCATS,
    "CHH": Team.CHARLOTTE_HORNETS,
    "SEA": Team.SEATTLE_SUPERSONICS,
    "STL": Team.ST_LOUIS_HAWKS,
    "VAN": Team.VANCOUVER_GRIZZLIES,
    "WSB": Team.WASHINGTON_BULLETS,
    # DEFUNCT BAA/NBA FRANCHISES
    "AND": Team.ANDERSON_PACKERS,
    "BLB": Team.BALTIMORE_BULLETS,
    "CHS": Team.CHICAGO_STAGS,
    "CLR": Team.CLEVELAND_REBELS,
    "DF": Team.DETROIT_FALCONS,
    "JET": Team.INDIANAPOLIS_JETS,
    "INO": Team.INDIANAPOLIS_OLYMPIANS,
    "PIT": Team.PITTSBURGH_IRONMEN,
    "PRS": Team.PROVIDENCE_STEAMROLLERS,
    "SHE": Team.SHEBOYGAN_RED_SKINS,
    "STB": Team.ST_LOUIS_BOMBERS,
    "TRH": Team.TORONTO_HUSKIES,
    "WAT": Team.WATERLOO_HAWKS,
    "CAP": Team.WASHINGTON_CAPITOLS,
}

TEAM_TO_TEAM_ABBREVIATION = {v: k for k, v in TEAM_ABBREVIATIONS_TO_TEAM.items()}
TEAM_TO_TEAM_ABBREVIATION[Team.CHARLOTTE_HORNETS] = "CHO"
# ``Team.BALTIMORE_BULLETS`` is the target of two BR abbreviations: ``BAL``
# (1963-1973 Wizards-lineage franchise) and ``BLB`` (defunct BAA franchise).
# Pin the canonical reverse abbreviation to ``BLB`` to preserve the existing
# (pre-``BAL``-mapping) serialisation behaviour.
TEAM_TO_TEAM_ABBREVIATION[Team.BALTIMORE_BULLETS] = "BLB"

TEAM_NAME_TO_TEAM = {
    "ATLANTA HAWKS": Team.ATLANTA_HAWKS,
    "BOSTON CELTICS": Team.BOSTON_CELTICS,
    "BROOKLYN NETS": Team.BROOKLYN_NETS,
    "CHARLOTTE HORNETS": Team.CHARLOTTE_HORNETS,
    "CHICAGO BULLS": Team.CHICAGO_BULLS,
    "CLEVELAND CAVALIERS": Team.CLEVELAND_CAVALIERS,
    "DALLAS MAVERICKS": Team.DALLAS_MAVERICKS,
    "DENVER NUGGETS": Team.DENVER_NUGGETS,
    "DETROIT PISTONS": Team.DETROIT_PISTONS,
    "GOLDEN STATE WARRIORS": Team.GOLDEN_STATE_WARRIORS,
    "HOUSTON ROCKETS": Team.HOUSTON_ROCKETS,
    "INDIANA PACERS": Team.INDIANA_PACERS,
    "LOS ANGELES CLIPPERS": Team.LOS_ANGELES_CLIPPERS,
    "LOS ANGELES LAKERS": Team.LOS_ANGELES_LAKERS,
    "MEMPHIS GRIZZLIES": Team.MEMPHIS_GRIZZLIES,
    "MIAMI HEAT": Team.MIAMI_HEAT,
    "MILWAUKEE BUCKS": Team.MILWAUKEE_BUCKS,
    "MINNESOTA TIMBERWOLVES": Team.MINNESOTA_TIMBERWOLVES,
    "NEW ORLEANS PELICANS": Team.NEW_ORLEANS_PELICANS,
    "NEW YORK KNICKS": Team.NEW_YORK_KNICKS,
    "OKLAHOMA CITY THUNDER": Team.OKLAHOMA_CITY_THUNDER,
    "ORLANDO MAGIC": Team.ORLANDO_MAGIC,
    "PHILADELPHIA 76ERS": Team.PHILADELPHIA_76ERS,
    "PHOENIX SUNS": Team.PHOENIX_SUNS,
    "PORTLAND TRAIL BLAZERS": Team.PORTLAND_TRAIL_BLAZERS,
    "SACRAMENTO KINGS": Team.SACRAMENTO_KINGS,
    "SAN ANTONIO SPURS": Team.SAN_ANTONIO_SPURS,
    "TORONTO RAPTORS": Team.TORONTO_RAPTORS,
    "UTAH JAZZ": Team.UTAH_JAZZ,
    "WASHINGTON WIZARDS": Team.WASHINGTON_WIZARDS,
    # DEPRECATED TEAMS
    "BUFFALO BRAVES": Team.BUFFALO_BRAVES,
    "CAPITAL BULLETS": Team.CAPITAL_BULLETS,
    "CHARLOTTE BOBCATS": Team.CHARLOTTE_BOBCATS,
    "CINCINNATI ROYALS": Team.CINCINNATI_ROYALS,
    "KANSAS CITY KINGS": Team.KANSAS_CITY_KINGS,
    "KANSAS CITY-OMAHA KINGS": Team.KANSAS_CITY_OMAHA_KINGS,
    "NEW JERSEY NETS": Team.NEW_JERSEY_NETS,
    "NEW ORLEANS HORNETS": Team.NEW_ORLEANS_HORNETS,
    "NEW ORLEANS/OKLAHOMA CITY HORNETS": Team.NEW_ORLEANS_OKLAHOMA_CITY_HORNETS,
    "PHILADELPHIA WARRIORS": Team.PHILADELPHIA_WARRIORS,
    "SAN FRANCISCO WARRIORS": Team.SAN_FRANCISCO_WARRIORS,
    "SEATTLE SUPERSONICS": Team.SEATTLE_SUPERSONICS,
    "ST. LOUIS HAWKS": Team.ST_LOUIS_HAWKS,
    "VANCOUVER GRIZZLIES": Team.VANCOUVER_GRIZZLIES,
    "WASHINGTON BULLETS": Team.WASHINGTON_BULLETS,
    # DEFUNCT BAA/NBA FRANCHISES
    "ANDERSON PACKERS": Team.ANDERSON_PACKERS,
    "BALTIMORE BULLETS": Team.BALTIMORE_BULLETS,
    "CHICAGO STAGS": Team.CHICAGO_STAGS,
    "CLEVELAND REBELS": Team.CLEVELAND_REBELS,
    "DETROIT FALCONS": Team.DETROIT_FALCONS,
    "INDIANAPOLIS JETS": Team.INDIANAPOLIS_JETS,
    "INDIANAPOLIS OLYMPIANS": Team.INDIANAPOLIS_OLYMPIANS,
    "PITTSBURGH IRONMEN": Team.PITTSBURGH_IRONMEN,
    "PROVIDENCE STEAMROLLERS": Team.PROVIDENCE_STEAMROLLERS,
    "SHEBOYGAN RED SKINS": Team.SHEBOYGAN_RED_SKINS,
    "ST. LOUIS BOMBERS": Team.ST_LOUIS_BOMBERS,
    "TORONTO HUSKIES": Team.TORONTO_HUSKIES,
    "WATERLOO HAWKS": Team.WATERLOO_HAWKS,
    "WASHINGTON CAPITOLS": Team.WASHINGTON_CAPITOLS,
}

POSITION_ABBREVIATIONS_TO_POSITION = {
    "PG": Position.POINT_GUARD,
    "SG": Position.SHOOTING_GUARD,
    "SF": Position.SMALL_FORWARD,
    "PF": Position.POWER_FORWARD,
    "C": Position.CENTER,
    "F": Position.FORWARD,
    "G": Position.GUARD,
}


LOCATION_ABBREVIATIONS_TO_LOCATION = {
    "": Location.HOME,
    "@": Location.AWAY,
}

# Deprecated alias (historical misnomer); prefer LOCATION_ABBREVIATIONS_TO_LOCATION.
LOCATION_ABBREVIATIONS_TO_POSITION = LOCATION_ABBREVIATIONS_TO_LOCATION


OUTCOME_ABBREVIATIONS_TO_OUTCOME = {
    "W": Outcome.WIN,
    "L": Outcome.LOSS,
}

LEAGUE_ABBREVIATIONS_TO_LEAGUE = {
    "NBA": League.NATIONAL_BASKETBALL_ASSOCIATION,
    "ABA": League.AMERICAN_BASKETBALL_ASSOCIATION,
    "BAA": League.BASKETBALL_ASSOCIATION_OF_AMERICA,
}
