"""Lookup dictionaries that map abbreviations to domain enum values."""

from courtside_data.domain.enums import (
    Conference,
    Division,
    League,
    Location,
    Outcome,
    Position,
    Team,
)

DIVISIONS_TO_CONFERENCES = {
    Division.ATLANTIC: Conference.EASTERN,
    Division.CENTRAL: Conference.EASTERN,
    Division.EASTERN: Conference.EASTERN,
    Division.SOUTHEAST: Conference.EASTERN,
    Division.MIDWEST: Conference.WESTERN,
    Division.PACIFIC: Conference.WESTERN,
    Division.SOUTHWEST: Conference.WESTERN,
    Division.NORTHWEST: Conference.WESTERN,
    Division.WESTERN: Conference.WESTERN,
}


TEAM_ABBREVIATIONS_TO_TEAM = {
    "ATL": Team.ATLANTA_HAWKS,
    "BOS": Team.BOSTON_CELTICS,
    "BRK": Team.BROOKLYN_NETS,
    "CHI": Team.CHICAGO_BULLS,
    "CHO": Team.CHARLOTTE_HORNETS,
    "CLE": Team.CLEVELAND_CAVALIERS,
    "DAL": Team.DALLAS_MAVERICKS,
    "DEN": Team.DENVER_NUGGETS,
    "DET": Team.DETROIT_PISTONS,
    "GSW": Team.GOLDEN_STATE_WARRIORS,
    "HOU": Team.HOUSTON_ROCKETS,
    "IND": Team.INDIANA_PACERS,
    "LAC": Team.LOS_ANGELES_CLIPPERS,
    "LAL": Team.LOS_ANGELES_LAKERS,
    "MEM": Team.MEMPHIS_GRIZZLIES,
    "MIA": Team.MIAMI_HEAT,
    "MIL": Team.MILWAUKEE_BUCKS,
    "MIN": Team.MINNESOTA_TIMBERWOLVES,
    "NOP": Team.NEW_ORLEANS_PELICANS,
    "NYK": Team.NEW_YORK_KNICKS,
    "OKC": Team.OKLAHOMA_CITY_THUNDER,
    "ORL": Team.ORLANDO_MAGIC,
    "PHI": Team.PHILADELPHIA_76ERS,
    "PHO": Team.PHOENIX_SUNS,
    "POR": Team.PORTLAND_TRAIL_BLAZERS,
    "SAC": Team.SACRAMENTO_KINGS,
    "SAS": Team.SAN_ANTONIO_SPURS,
    "TOR": Team.TORONTO_RAPTORS,
    "UTA": Team.UTAH_JAZZ,
    "WAS": Team.WASHINGTON_WIZARDS,
    # DEPRECATED TEAMS
    "BUF": Team.BUFFALO_BRAVES,
    # 1963-73 Baltimore Bullets (Wizards lineage, abbreviated ``BAL`` by
    # Basketball Reference) — distinct from the BAA-era Bullets (``BLB``);
    # see :class:`courtside_data.domain.enums.Team.BALTIMORE_BULLETS_WIZ`.
    # The reverse map is built from this forward map (``{v: k for k, v in
    # ...}``), so ``Team.BALTIMORE_BULLETS_WIZ`` -> ``"BAL"`` is added
    # automatically; the existing ``Team.BALTIMORE_BULLETS`` -> ``"BLB"``
    # override below pins the BAA franchise's canonical abbreviation.
    "BAL": Team.BALTIMORE_BULLETS_WIZ,
    "CIN": Team.CINCINNATI_ROYALS,
    "KCK": Team.KANSAS_CITY_KINGS,
    "KCO": Team.KANSAS_CITY_OMAHA_KINGS,
    "NJN": Team.NEW_JERSEY_NETS,
    "NOH": Team.NEW_ORLEANS_HORNETS,
    "NOK": Team.NEW_ORLEANS_OKLAHOMA_CITY_HORNETS,
    "PHW": Team.PHILADELPHIA_WARRIORS,
    "SFW": Team.SAN_FRANCISCO_WARRIORS,
    "CHA": Team.CHARLOTTE_BOBCATS,
    "CHH": Team.CHARLOTTE_HORNETS,
    "SEA": Team.SEATTLE_SUPERSONICS,
    "STL": Team.ST_LOUIS_HAWKS,
    "VAN": Team.VANCOUVER_GRIZZLIES,
    "WSB": Team.WASHINGTON_BULLETS,
    # DEFUNCT BAA/NBA FRANCHISES
    "AND": Team.ANDERSON_PACKERS,
    "BLB": Team.BALTIMORE_BULLETS,
    "CHS": Team.CHICAGO_STAGS,
    "CLR": Team.CLEVELAND_REBELS,
    "DTF": Team.DETROIT_FALCONS,
    "INJ": Team.INDIANAPOLIS_JETS,
    "INO": Team.INDIANAPOLIS_OLYMPIANS,
    "PIT": Team.PITTSBURGH_IRONMEN,
    "PRO": Team.PROVIDENCE_STEAMROLLERS,
    "SHE": Team.SHEBOYGAN_RED_SKINS,
    "STB": Team.ST_LOUIS_BOMBERS,
    "TRH": Team.TORONTO_HUSKIES,
    "WAT": Team.WATERLOO_HAWKS,
    "WSC": Team.WASHINGTON_CAPITOLS,
    # HISTORICAL NBA/BAA FRANCHISE ERAS
    "CAP": Team.CAPITAL_BULLETS,
    "CHP": Team.CHICAGO_PACKERS,
    "CHZ": Team.CHICAGO_ZEPHYRS,
    "DNN": Team.DENVER_NUGGETS_1949,
    "FTW": Team.FORT_WAYNE_PISTONS,
    "MLH": Team.MILWAUKEE_HAWKS,
    "MNL": Team.MINNEAPOLIS_LAKERS,
    "NOJ": Team.NEW_ORLEANS_JAZZ,
    "ROC": Team.ROCHESTER_ROYALS,
    "SDC": Team.SAN_DIEGO_CLIPPERS,
    "SDR": Team.SAN_DIEGO_ROCKETS,
    "SYR": Team.SYRACUSE_NATIONALS,
    "TRI": Team.TRI_CITIES_BLACKHAWKS,
    # ABA FRANCHISES
    "CAR": Team.CAROLINA_COUGARS,
    "DNR": Team.DENVER_ROCKETS,
    "INA": Team.INDIANA_PACERS_ABA,
    "KEN": Team.KENTUCKY_COLONELS,
    "MMS": Team.MEMPHIS_SOUNDS,
    "MMT": Team.MEMPHIS_TAMS,
    "NOB": Team.NEW_ORLEANS_BUCCANEERS,
    "NYA": Team.NEW_YORK_NETS_ABA,
    "OAK": Team.OAKLAND_OAKS,
    "PTC": Team.PITTSBURGH_CONDORS,
    "SAA": Team.SAN_ANTONIO_SPURS_ABA,
    "SDA": Team.SAN_DIEGO_CONQUISTADORS,
    "SDS": Team.SAN_DIEGO_SAILS,
    "SSL": Team.SPIRITS_OF_ST_LOUIS,
    "UTS": Team.UTAH_STARS,
    "VIR": Team.VIRGINIA_SQUIRES,
}

TEAM_TO_TEAM_ABBREVIATION = {v: k for k, v in TEAM_ABBREVIATIONS_TO_TEAM.items()}
TEAM_TO_TEAM_ABBREVIATION[Team.CHARLOTTE_HORNETS] = "CHO"
TEAM_TO_TEAM_ABBREVIATION[Team.CAPITAL_BULLETS] = "CAP"
TEAM_TO_TEAM_ABBREVIATION[Team.DETROIT_FALCONS] = "DTF"
TEAM_TO_TEAM_ABBREVIATION[Team.INDIANAPOLIS_JETS] = "INJ"
TEAM_TO_TEAM_ABBREVIATION[Team.PROVIDENCE_STEAMROLLERS] = "PRO"
# ``Team.BALTIMORE_BULLETS`` is the BAA-era franchise; its only BR
# abbreviation is ``BLB`` (the ``BAL`` abbreviation now resolves to
# ``Team.BALTIMORE_BULLETS_WIZ`` — the 1963-73 Wizards-lineage Bullets).
# Pin the canonical reverse abbreviation to ``BLB`` to preserve the
# existing (pre-``BAL``-mapping) serialisation behaviour.
TEAM_TO_TEAM_ABBREVIATION[Team.BALTIMORE_BULLETS] = "BLB"

TEAM_NAME_TO_TEAM = {
    "ATLANTA HAWKS": Team.ATLANTA_HAWKS,
    "BOSTON CELTICS": Team.BOSTON_CELTICS,
    "BROOKLYN NETS": Team.BROOKLYN_NETS,
    "CHARLOTTE HORNETS": Team.CHARLOTTE_HORNETS,
    "CHICAGO BULLS": Team.CHICAGO_BULLS,
    "CLEVELAND CAVALIERS": Team.CLEVELAND_CAVALIERS,
    "DALLAS MAVERICKS": Team.DALLAS_MAVERICKS,
    "DENVER NUGGETS": Team.DENVER_NUGGETS,
    "DETROIT PISTONS": Team.DETROIT_PISTONS,
    "GOLDEN STATE WARRIORS": Team.GOLDEN_STATE_WARRIORS,
    "HOUSTON ROCKETS": Team.HOUSTON_ROCKETS,
    "INDIANA PACERS": Team.INDIANA_PACERS,
    "LOS ANGELES CLIPPERS": Team.LOS_ANGELES_CLIPPERS,
    "LOS ANGELES LAKERS": Team.LOS_ANGELES_LAKERS,
    "MEMPHIS GRIZZLIES": Team.MEMPHIS_GRIZZLIES,
    "MIAMI HEAT": Team.MIAMI_HEAT,
    "MILWAUKEE BUCKS": Team.MILWAUKEE_BUCKS,
    "MINNESOTA TIMBERWOLVES": Team.MINNESOTA_TIMBERWOLVES,
    "NEW ORLEANS PELICANS": Team.NEW_ORLEANS_PELICANS,
    "NEW YORK KNICKS": Team.NEW_YORK_KNICKS,
    "OKLAHOMA CITY THUNDER": Team.OKLAHOMA_CITY_THUNDER,
    "ORLANDO MAGIC": Team.ORLANDO_MAGIC,
    "PHILADELPHIA 76ERS": Team.PHILADELPHIA_76ERS,
    "PHOENIX SUNS": Team.PHOENIX_SUNS,
    "PORTLAND TRAIL BLAZERS": Team.PORTLAND_TRAIL_BLAZERS,
    "SACRAMENTO KINGS": Team.SACRAMENTO_KINGS,
    "SAN ANTONIO SPURS": Team.SAN_ANTONIO_SPURS,
    "TORONTO RAPTORS": Team.TORONTO_RAPTORS,
    "UTAH JAZZ": Team.UTAH_JAZZ,
    "WASHINGTON WIZARDS": Team.WASHINGTON_WIZARDS,
    # DEPRECATED TEAMS
    "BUFFALO BRAVES": Team.BUFFALO_BRAVES,
    "CAPITAL BULLETS": Team.CAPITAL_BULLETS,
    "CHARLOTTE BOBCATS": Team.CHARLOTTE_BOBCATS,
    "CINCINNATI ROYALS": Team.CINCINNATI_ROYALS,
    "KANSAS CITY KINGS": Team.KANSAS_CITY_KINGS,
    "KANSAS CITY-OMAHA KINGS": Team.KANSAS_CITY_OMAHA_KINGS,
    "NEW JERSEY NETS": Team.NEW_JERSEY_NETS,
    "NEW ORLEANS HORNETS": Team.NEW_ORLEANS_HORNETS,
    "NEW ORLEANS/OKLAHOMA CITY HORNETS": Team.NEW_ORLEANS_OKLAHOMA_CITY_HORNETS,
    "PHILADELPHIA WARRIORS": Team.PHILADELPHIA_WARRIORS,
    "SAN FRANCISCO WARRIORS": Team.SAN_FRANCISCO_WARRIORS,
    "SEATTLE SUPERSONICS": Team.SEATTLE_SUPERSONICS,
    "ST. LOUIS HAWKS": Team.ST_LOUIS_HAWKS,
    "VANCOUVER GRIZZLIES": Team.VANCOUVER_GRIZZLIES,
    "WASHINGTON BULLETS": Team.WASHINGTON_BULLETS,
    # HISTORICAL NBA/BAA FRANCHISE ERAS
    "CHICAGO PACKERS": Team.CHICAGO_PACKERS,
    "CHICAGO ZEPHYRS": Team.CHICAGO_ZEPHYRS,
    "DENVER NUGGETS (1949-50)": Team.DENVER_NUGGETS_1949,
    "FORT WAYNE PISTONS": Team.FORT_WAYNE_PISTONS,
    "MILWAUKEE HAWKS": Team.MILWAUKEE_HAWKS,
    "MINNEAPOLIS LAKERS": Team.MINNEAPOLIS_LAKERS,
    "NEW ORLEANS JAZZ": Team.NEW_ORLEANS_JAZZ,
    "ROCHESTER ROYALS": Team.ROCHESTER_ROYALS,
    "SAN DIEGO CLIPPERS": Team.SAN_DIEGO_CLIPPERS,
    "SAN DIEGO ROCKETS": Team.SAN_DIEGO_ROCKETS,
    "SYRACUSE NATIONALS": Team.SYRACUSE_NATIONALS,
    "TRI-CITIES BLACKHAWKS": Team.TRI_CITIES_BLACKHAWKS,
    # ABA FRANCHISES
    "CAROLINA COUGARS": Team.CAROLINA_COUGARS,
    "DENVER ROCKETS": Team.DENVER_ROCKETS,
    "INDIANA PACERS (ABA)": Team.INDIANA_PACERS_ABA,
    "KENTUCKY COLONELS": Team.KENTUCKY_COLONELS,
    "MEMPHIS SOUNDS": Team.MEMPHIS_SOUNDS,
    "MEMPHIS TAMS": Team.MEMPHIS_TAMS,
    "NEW ORLEANS BUCCANEERS": Team.NEW_ORLEANS_BUCCANEERS,
    "NEW YORK NETS (ABA)": Team.NEW_YORK_NETS_ABA,
    "OAKLAND OAKS": Team.OAKLAND_OAKS,
    "PITTSBURGH CONDORS": Team.PITTSBURGH_CONDORS,
    "SAN ANTONIO SPURS (ABA)": Team.SAN_ANTONIO_SPURS_ABA,
    "SAN DIEGO CONQUISTADORS": Team.SAN_DIEGO_CONQUISTADORS,
    "SAN DIEGO SAILS": Team.SAN_DIEGO_SAILS,
    "SPIRITS OF ST. LOUIS": Team.SPIRITS_OF_ST_LOUIS,
    "UTAH STARS": Team.UTAH_STARS,
    "VIRGINIA SQUIRES": Team.VIRGINIA_SQUIRES,
    # DEFUNCT BAA/NBA FRANCHISES
    "ANDERSON PACKERS": Team.ANDERSON_PACKERS,
    "BALTIMORE BULLETS": Team.BALTIMORE_BULLETS,
    "CHICAGO STAGS": Team.CHICAGO_STAGS,
    "CLEVELAND REBELS": Team.CLEVELAND_REBELS,
    "DETROIT FALCONS": Team.DETROIT_FALCONS,
    "INDIANAPOLIS JETS": Team.INDIANAPOLIS_JETS,
    "INDIANAPOLIS OLYMPIANS": Team.INDIANAPOLIS_OLYMPIANS,
    "PITTSBURGH IRONMEN": Team.PITTSBURGH_IRONMEN,
    "PROVIDENCE STEAMROLLERS": Team.PROVIDENCE_STEAMROLLERS,
    "SHEBOYGAN RED SKINS": Team.SHEBOYGAN_RED_SKINS,
    "ST. LOUIS BOMBERS": Team.ST_LOUIS_BOMBERS,
    "TORONTO HUSKIES": Team.TORONTO_HUSKIES,
    "WATERLOO HAWKS": Team.WATERLOO_HAWKS,
    "WASHINGTON CAPITOLS": Team.WASHINGTON_CAPITOLS,
}

POSITION_ABBREVIATIONS_TO_POSITION = {
    "PG": Position.POINT_GUARD,
    "SG": Position.SHOOTING_GUARD,
    "SF": Position.SMALL_FORWARD,
    "PF": Position.POWER_FORWARD,
    "C": Position.CENTER,
    "F": Position.FORWARD,
    "G": Position.GUARD,
}


LOCATION_ABBREVIATIONS_TO_LOCATION = {
    "": Location.HOME,
    "@": Location.AWAY,
}


OUTCOME_ABBREVIATIONS_TO_OUTCOME = {
    "W": Outcome.WIN,
    "L": Outcome.LOSS,
}

LEAGUE_ABBREVIATIONS_TO_LEAGUE = {
    "NBA": League.NATIONAL_BASKETBALL_ASSOCIATION,
    "ABA": League.AMERICAN_BASKETBALL_ASSOCIATION,
    "BAA": League.BASKETBALL_ASSOCIATION_OF_AMERICA,
}
